=== ola567/Projekt-z-przedmiotu-Hipertekst-i-Hipermedia/Hein_Aleksandra_184717/DTD.dtd
<!ELEMENT culinaryart (project, introduction, recipes, survey)>

<!ENTITY % project "date, Name, Surname, age, tel, country">
<!ENTITY % survey "heading, description, question+">
<!ENTITY % content "oddity+, oddityextra, table">
<!ENTITY coos "Smacznego!">

<!ELEMENT project (%project;)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Surname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT introduction (entry, article)>
<!ELEMENT entry (#PCDATA | media)*>
<!ELEMENT media (img)>
<!ELEMENT img (#PCDATA)>
<!ELEMENT article (description, content)>
<!ELEMENT description (#PCDATA | links)*>
<!ELEMENT links (link+)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT content (%content;)>
<!ELEMENT oddity (title, inside)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT inside (#PCDATA | media)*>
<!ELEMENT oddityextra (NAME, SURNAME, HISTORY)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT SURNAME (#PCDATA)>
<!ELEMENT HISTORY (#PCDATA)>
<!ELEMENT table (product+)>
<!ELEMENT product (#PCDATA | kcal)*>
<!ELEMENT kcal (#PCDATA)>

<!ELEMENT recipes (recipe+)>
<!ELEMENT recipe (r+)>
<!ELEMENT r (name, media, ingredients, howtodo)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ingredients (i+)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT howtodo (#PCDATA)>

<!ELEMENT survey (%survey;)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT question (#PCDATA | options | choices)*>
<!ELEMENT options (option+)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT choices (choice+)>
<!ELEMENT choice (#PCDATA)>

<!ATTLIST link source CDATA "https://dietetycy.org.pl/20-faktow-mitow-zywieniowych/">
<!ATTLIST link source CDATA "https://www.elle.pl/sport/artykul/fakty-i-mity-na-talerzu-zielona-herbata-odchudza-a-wegetarianizm-prowadzi-do-niedoboru-zelaza">
<!ATTLIST link source CDATA "https://dietatopodstawa.pl/porady/ciekawostki">
<!ATTLIST project informations CDATA "aboutAuthorAndProject">
<!ATTLIST oddityextra  id CDATA "najsłynniejszy_kucharz">
<!ATTLIST product number (1|2|3|4|5) "1">
<!ATTLIST recipe category (sniadanie|zupy|makarony|miesne|desery) #REQUIRED>
<!ATTLIST table tytul CDATA "kaloryczność">
<!ATTLIST culinaryart xmlns:xsi CDATA "http://www.w3.org/2001/XMLSchema-instance">
<!ATTLIST culinaryart  xsi:noNamespaceSchemaLocation CDATA "XSD.xsd">
<!ATTLIST img source CDATA "img/logo.svg">
<!ATTLIST img source CDATA "img/proszek.png">
<!ATTLIST img source CDATA "img/grill.png">
<!ATTLIST img source CDATA "img/granola.jpg">
<!ATTLIST img source CDATA "img/roladki.jpg">
<!ATTLIST img source CDATA "img/grzybowa.jpg">
<!ATTLIST img source CDATA "img/por.jpg">
<!ATTLIST img source CDATA "img/makaron1.jpg">
<!ATTLIST img source CDATA "img/kurczak.jpg">
<!ATTLIST img source CDATA "img/owsiane.jpg">
<!ATTLIST img source CDATA "img/makaron.jpg">

=== ola567/Projekt-z-przedmiotu-Hipertekst-i-Hipermedia/Hein_Aleksandra_184717/XML.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE culinaryart SYSTEM "DTD.dtd">

<culinaryart xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="XSD.xsd">

  <project informations="aboutAuthorAndProject">
    <date>2020-11-29</date>
    <Name>Aleksandra</Name>
    <Surname>Hein</Surname>
    <age>19</age>
    <tel>123 456 789</tel>
    <country>Polska</country>
  </project>

  <introduction>
    <entry>
        Kilka słów na początek...
        Gotowanie od zawsze było moją pasją. Lubiłam ( i oczywiście nadal lubię :) ) smakować nowe potrawy, próbować nowych przepisów, a nawet wymyślać swoje, autorskie dania. Tworzenie nowych potraw sprawia mi niezwykłą frajdę, co niewątpiliwe przynosi korzyści również moim znajomym i rodzinie, którzy zawsze się załapią na jakiś obiadek i ciastko. Chciałabym na tej stornie internetowej pokazać kilka swoich przepisów, które mam nadzieję trafią w Wasze gusta. Przygotowałam również quiz dotyczący różnych produktów. Serdecznie zapraszam do miłej lektury.
        <media>
          <img source="img/logo.svg">logo</img>
        </media>
    </entry>
    <article>
      <description>
        A oto przed wami 2 ciekawostki dotyczących odżywiania (tak dla rozbudzenia ciekawości :) ). To niewiele, ale zawsze po więcej informacji można sięgnąć do dietetycy.org.pl, elle.pl, dietatopodstawa.pl, czy też i innych stron internetowych.
        <links>
          <link source="https://dietetycy.org.pl/20-faktow-mitow-zywieniowych/">dietetycy.org.pl</link>
          <link source="https://www.elle.pl/sport/artykul/fakty-i-mity-na-talerzu-zielona-herbata-odchudza-a-wegetarianizm-prowadzi-do-niedoboru-zelaza">elle.pl</link>
          <link source="https://dietatopodstawa.pl/porady/ciekawostki">dietatopodstawa.pl</link>
        </links> 
      </description>
      <content>
        <oddity>
          <title>Jedzenie posiłków z proszku zamiast normalnych dań to skuteczny sposób odchudzania.</title>
          <inside>Fakt, można w ten sposób szybko stracić kilka, a nawet kilkanaście kilogramów, lecz organizm po zakończeniu odchudzania przystąpi do odbudowy zapasów. Efekt jo-jo zapewniony. Długie stosowanie diety proszkowej prowadzi do niedoboru witamin i minerałów, osłabienia organizmu i ciężkich depresji.
            <media>
              <img source="img/proszek.png">proszek</img>
            </media>
          </inside>
        </oddity>
        <oddity>
          <title>Grillowane mięsa są rakotwórcze</title>
          <inside>Nieprawda. Grillowanie jest jednym z najlepszych sposobów przyrządzania mięsa. Jeśli wybierzemy niezbyt tłuste gatunki, np. polędwicę wołową lub cielęcą, rostbef, łopatkę, udziec cielęcy, karkówkę czy szynkę, i będziemy piekli je bez tłuszczu, z dużą ilością przypraw, danie będzie nie tylko smaczne, ale i dietetyczne. Zioła ułatwiają trawienie i mogą zastąpić sól, której nadmiar jest dla organizmu szkodliwy. Mięso z grilla bywa niebezpieczne jedynie wtedy, gdy tłuszcz wytapiający się z niego kapie bezpośrednio na rozgrzany ruszt. Wtedy właśnie powstają rakotwórcze substancje gazowe, tzw. dioksany. Możemy tego uniknąć, umieszczając mięso na aluminiowej tacce lub w folii. Podobnie powinniśmy postępować z grillowanymi warzywami.
            <media>
              <img source="img/grill.png">grill</img>
            </media>
          </inside>
        </oddity>
        <oddityextra id="najsłynniejszy_kucharz">
          <NAME>Paul</NAME>
          <SURNAME>Bocuse</SURNAME>
          <HISTORY>
            Pochodził z rodziny kucharzy. W wieku 16 lat rozpoczął praktykę w restauracji de la Soierie w Lyonie. W 1944, w wieku 18 lat, wstąpił na ochotnika do Armii Wolnych Francuzów i walczył w składzie 1 dywizji. Po zakończeniu wojny powrócił do Lyonu, gdzie uczył się pod kierunkiem Eugénie Braziera, a następnie w Paryżu u Gastona Richarda. Zaliczany jest do pionierów nowej kuchni francuskiej (nouvelle cuisine), bardziej dietetycznej niż tradycyjna kuchnia francuska (cuisine classique) z uwagi na wykorzystywanie wyłącznie świeżych produktów. W 1975 na obiedzie prezydenckim w Pałacu Elizejskim podano jedno z najsłynniejszych dań Bocuse'a – zupę z trufli (soupe aux truffes). Danie to stało się potem wizytówką restauracji Soupe V.G.E. w pobliżu Lyonu (inicjały V.G.E. odnosiły się do prezydenta Valéry’ego Giscarda d’Estaing). Za najbardziej znaną restauracją Bocuse'a uchodziła l'Auberge du Pont de Collonges w Collonges-au-Mont-d’Or, wyróżniona trzema gwiazdkami w przewodniku Michelina. Sieć restauracji tematycznych Bocuse'a, działająca w Lyonie, oferuje różne odmiany kuchni francuskiej. Instytut noszący imię francuskiego kuchmistrza organizuje czteromiesięczne szkolenia z zakresu regionalnej kuchni francuskiej i doboru win dla studentów z dziewięciu uniwersytetów, tworzących sieć Paul Bocuse Worldwide Alliance. W gronie uczniów Bocuse'a znajduje się kilku kuchmistrzów o międzynarodowej sławie, w tym Austriak Eckart Witzigmann, pierwszy kucharz z kraju niemieckojęzycznego, którego restauracja otrzymała trzy gwiazdki w przewodniku Michelina. Przyznawana od 1987 nagroda Złotego Bocuse'a (Bocuse d’Or) uchodzi za jedno z najbardziej prestiżowych wyróżnień dla szefów kuchni na świecie. The Culinary Institute of America w 2011 nagrodził Paula Bocuse'a tytułem Kuchmistrza Stulecia (Chef of the Century). W 1975 został komandorem Legii Honorowej. Syn Paula Bocuse'a, Jérôme, kieruje restauracją w pawilonie francuskim w amerykańskim Walt Disney World Resort w Orlando.
          </HISTORY>
        </oddityextra>
        <table tytul="kaloryczność">
          <product number="1">
            Masło orzechowe
            <kcal>589</kcal>
          </product>
          <product number="2">
            Skwarki
            <kcal>579</kcal>
          </product>
          <product number="3">
            Big Mac
            <kcal>550</kcal>
          </product>
          <product number="4">
            Mocaccino
            <kcal>461</kcal>
          </product>
          <product number="5">
            Kokos
            <kcal>370</kcal>
          </product>
        </table>
      </content>
    </article>
  </introduction>

  <recipes>
    <recipe category="sniadanie">
      <r>
        <name>Granola z żurawiną</name>
        <media>
             <img source="img/granola.jpg">granola</img>
        </media>
        <ingredients>
          <i>2 łyżki kakao</i>
          <i>0,5 szklanki żurawuny</i>
          <i>2 szklanki płatków owsianych</i>
          <i>2 łyżki miodu</i>
          <i>0,5 szklanki orzechów włoskich</i>
        </ingredients>
        <howtodo>
          Nastaw piekarnik na 180 st. C. Blaszkę wyłóż papierem do pieczenia.
          Orzechy i żurawinę posiekaj na drobne kawałki.
          W rondelku podgrzej miód oraz kakao. Jak tylko miód się rozpuści i połączy z kakao, zdejmij rondel z ognia.
          Do rondelka wsyp płatki owsiane oraz pokrojoną żurawinę i orzechy. Mieszaj do połączenia się wszystkich składników i wysyp na przygotowaną wcześniej blaszkę.
          Piecz w piekarniku przez ok. 20 min. Ostudź i rozdrobnij.
          Gotową granole przechowuj w szczelnie zamkniętym pojemniku. Idealna z mlekiem, jogurtem czy solo jako przekąska. &coos;
        </howtodo>
      </r>
      <r>
        <name>Roladki z tortilli</name>
        <media>
             <img source="img/roladki.jpg">tortilla</img>
        </media>
        <ingredients>
          <i>1 puszka Kukurydzy złocistej z czerwoną fasolą Bonduelle 212 ml</i>
          <i>150 g grillowanej papryki</i>
          <i>120 g majonezu</i>
          <i>100 g żółtego sera o intensywnym smaku</i>
          <i>60 g pikantnego ketchupu</i>
          <i>3 pszenne tortille</i>
          <i>1 dymka</i>
          <i>0,5 główki sałaty</i>
          <i>0,5 łyżeczki oregano</i>
          <i>sól i pieprz</i>
        </ingredients>
        <howtodo>
          Paprykę kroimy w paski, dymkę w talarki. Oddzielamy liście sałaty. Majonez mieszamy z ketchupem. Doprawiamy oregano, solą i pieprzem, jeśli to konieczne.Ser ścieramy na tarce o grubych oczkach. Każdą tortillę smarujemy przygotowanym sosem i posypujemy tartym serem, osączoną z zalewy kukurydzą z fasolą, dymką oraz papryką. Układamy liście sałaty. Rolujemy ściśle tortille i kroimy je na kawałki ostrym nożem. &coos;
        </howtodo>
      </r>
    </recipe>
    <recipe category="zupy">
      <r>
        <name>Grzybowa z suszonych grzybów</name>
        <media>
             <img source="img/grzybowa.jpg">grzybowa</img>
        </media>
        <ingredients>
          <i>70 g grzybów suszonych (borowików i/lub podgrzybków</i>
          <i>1,5 litra bulionu (np. grzybowy, warzywny, mięsny)</i>
          <i>1 łyżka oleju roślinnego</i>
          <i>1 cebula</i>
          <i>1 marchewka</i>
          <i>2 ziemniaki</i>
          <i>zioła: po 1 łyżeczce tymianku, cząbru i majeranku</i>
          <i>pęczek natki pietruszki</i>
          <i>250 ml śmietanki 30%</i>
          <i>do podania: grzaneczki z chleba</i>
        </ingredients>
        <howtodo>
          Suszone grzyby opłukać pod bieżącą chłodną wodą, włożyć do miski, zalać bulionem i odstawić na noc do namoczenia.
          Do większego garnka wlać oliwę i zeszklić pokrojoną w kosteczkę cebulę.
          Następnie dodać obraną i startą na tarce marchewkę i podsmażać przez ok. 2 minuty.
          Dodać obrane i pokrojone w kostkę ziemniaki oraz zioła. Mieszając co chwilę podsmażać przez minutę.
          Wlać namoczone grzyby wraz z bulionem. Zagotować na dużym ogniu. Doprawić solą i pieprzem (ok. pół łyżeczki).
          Po zagotowaniu zmniejszyć ogień i gotować pod przykryciem przez ok. 20 minut (do miękkości składników).
          Odstawić z ognia i zmiksować z dodatkiem oderwanych listków natki pietruszki oraz śmietanki.
